# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.text_physical_address_annotation import TextPhysicalAddressAnnotation
from openapi_server import util

from openapi_server.models.text_physical_address_annotation import TextPhysicalAddressAnnotation  # noqa: E501

class TextPhysicalAddressAnnotations(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text_date_annotations=None):  # noqa: E501
        """TextPhysicalAddressAnnotations - a model defined in OpenAPI

        :param text_date_annotations: The text_date_annotations of this TextPhysicalAddressAnnotations.  # noqa: E501
        :type text_date_annotations: List[TextPhysicalAddressAnnotation]
        """
        self.openapi_types = {
            'text_date_annotations': List[TextPhysicalAddressAnnotation]
        }

        self.attribute_map = {
            'text_date_annotations': 'textDateAnnotations'
        }

        self._text_date_annotations = text_date_annotations

    @classmethod
    def from_dict(cls, dikt) -> 'TextPhysicalAddressAnnotations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextPhysicalAddressAnnotations of this TextPhysicalAddressAnnotations.  # noqa: E501
        :rtype: TextPhysicalAddressAnnotations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text_date_annotations(self):
        """Gets the text_date_annotations of this TextPhysicalAddressAnnotations.

        A list of text physical address annotations  # noqa: E501

        :return: The text_date_annotations of this TextPhysicalAddressAnnotations.
        :rtype: List[TextPhysicalAddressAnnotation]
        """
        return self._text_date_annotations

    @text_date_annotations.setter
    def text_date_annotations(self, text_date_annotations):
        """Sets the text_date_annotations of this TextPhysicalAddressAnnotations.

        A list of text physical address annotations  # noqa: E501

        :param text_date_annotations: The text_date_annotations of this TextPhysicalAddressAnnotations.
        :type text_date_annotations: List[TextPhysicalAddressAnnotation]
        """

        self._text_date_annotations = text_date_annotations
